In [1]:
import pandas as pd

In [2]:
compaines = pd.read_csv('../../datasets/fortune1000.csv')

In [3]:
compaines.head()

,Rank,Company,Sector,Industry,Location,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
2,3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
3,4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
4,5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [4]:
compaines.set_index(['Rank'], inplace=True)

In [5]:
compaines.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [6]:
compaines.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1 to 1000
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Company    1000 non-null   object
 1   Sector     1000 non-null   object
 2   Industry   1000 non-null   object
 3   Location   1000 non-null   object
 4   Revenue    1000 non-null   int64
 5   Profits    1000 non-null   int64
 6   Employees  1000 non-null   int64
dtypes: int64(3), object(4)
memory usage: 62.5+ KB

In [7]:
compaines.nunique()

Company      996
Sector        21
Industry      73
Location     416
Revenue      945
Profits      760
Employees    755
dtype: int64

### The ideal thing we want to group by is that the column to have duplicate values. This means we want to create a segments of our dataset.
##### There's no point grouping on company because all the companies are unique in the dataset.
##### A column like sector is perfect to group by. E.g, under Energy sector group, all the companies can come
#### A group by is a method called on a dataframe
#### It returns a dataframe group by object

In [8]:
sectors = compaines.groupby(by='Sector')

In [9]:
sectors

In [10]:
sectors.size()
# how many times each sector is present

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [11]:
compaines.Sector.value_counts()

Financials                      139
Energy                          122
Technology                      102
Retailing                        80
Health Care                      75
Business Services                51
Industrials                      46
Materials                        43
Food, Beverages & Tobacco        43
Wholesalers                      40
Transportation                   36
Chemicals                        30
Household Products               28
Engineering & Construction       26
Media                            25
Hotels, Resturants & Leisure     25
Motor Vehicles & Parts           24
Aerospace & Defense              20
Telecommunications               15
Food and Drug Stores             15
Apparel                          15
Name: Sector, dtype: int64

In [12]:
sectors.first()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,"Chicago, IL",96114,5176,161400
Apparel,Nike,Apparel,"Beaverton, OR",30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,"Milwaukee, WI",19330,419,27000
Chemicals,Dow Chemical,Chemicals,"Midland, MI",48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction","Irving, TX",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,"Chicago, IL",67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,"Oak Brook, IL",25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
Industrials,General Electric,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
Materials,Alcoa,Metals,"New York, NY",22534,-322,60000
Media,Disney,Entertainment,"Burbank, CA",52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
Retailing,Walmart,General Merchandisers,"Bentonville, AR",482130,14694,2300000
Technology,Apple,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
Telecommunications,AT&T,Telecommunications,"Dallas, TX",146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [13]:
sectors.last()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Delta Tucker Holdings,Aerospace and Defense,"McLean, VA",1923,-133,12000
Apparel,Guess,Apparel,"Los Angeles, CA",2204,82,13500
Business Services,DeVry Education Group,Education,"Downers Grove, IL",1910,140,11770
Chemicals,H.B. Fuller,Chemicals,"St. Paul, MN",2084,87,4425
Energy,Portland General Electric,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
Engineering & Construction,MDC Holdings,Homebuilders,"Denver, CO",1909,66,1225
Financials,New York Community Bancorp,Commercial Banks,"Westbury, NY",1902,-47,3448
Food and Drug Stores,Fred’s,Food and Drug Stores,"Memphis, TN",2151,-7,7103
"Food, Beverages & Tobacco",Alliance One International,Tobacco,"Morrisville, NC",2066,-15,6835
Health Care,Providence Service,Health Care: Pharmacy and Other Services,"Tucson, AZ",1987,84,9072
"Hotels, Resturants & Leisure",Wendy’s,Food Services,"Dublin, OH",1896,161,21200
Household Products,Revlon,Household and Personal Products,"New York, NY",1914,56,5700
Industrials,Briggs & Stratton,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
Materials,Schnitzer Steel Industries,Metals,"Portland, OR",1924,-197,2955
Media,Cenveo,"Publishing, Printing","Stamford, CT",1921,-31,7300
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,"Indianaoplis, IN",1986,182,2700
Retailing,99 Cents Only Stores,Specialty Retailers: Other,"Commerce, CA",1999,-232,18200
Technology,F5 Networks,Network and Other Communications Equipment,"Seattle, WA",1920,365,4178
Telecommunications,Equinix,Telecommunications,"Redwood City, CA",2726,188,5042
Transportation,Roadrunner Transportation Systems,Transportation and Logistics,"Cudahy, WI",1995,48,4502
Wholesalers,BlueLinx Holdings,Wholesalers: Diversified,"Atlanta, GA",1917,-12,1600

#### ^^^ Able to extract sample rows from the very top and very end of each grouping

In [14]:
sectors.groups

{'Aerospace & Defense': [24, 45, 60, 88, 118, 120, 209, 245, 282, 378, 389, 490, 560, 605, 785, 788, 836, 903, 958, 987], 'Apparel': [91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877, 882, 917], 'Business Services': [144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404, 440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694, 714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796, 801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993], 'Chemicals': [56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549, 555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829, 865, 898, 934, 949], 'Energy': [2, 14, 30, 32, 42, 65, 90, 95, 98, 104, 115, 117, 121, 162, 163, 165, 166, 175, 178, 188, 190, 192, 193, 198, 214, 216, 217, 223, 225, 229, 243, 246, 247, 257, 272, 274, 279, 289, 319, 322, 324, 343, 348, 349, 350, 363, 364, 384, 387, 388, 394, 402, 403, 410, 425, 437, 438, 445, 458, 475, 483, 493, 507, 522, 541, 548, 556, 558, 569, 571, 579, 598, 600, 606, 633, 650, 656, 662, 679, 692, 696, 703, 703, 706, 711, 715, 732, 742, 743, 745, 754, 772, 784, 798, 802, 810, 817, 826, 843, 850, ...], 'Engineering & Construction': [155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516, 572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994], 'Financials': [4, 16, 23, 26, 27, 29, 35, 40, 43, 49, 50, 61, 69, 73, 74, 76, 78, 81, 82, 83, 85, 100, 105, 112, 114, 131, 135, 137, 152, 171, 179, 184, 205, 210, 222, 226, 227, 232, 236, 250, 252, 259, 264, 265, 271, 273, 275, 283, 298, 306, 311, 318, 326, 329, 332, 344, 347, 367, 368, 376, 382, 398, 401, 411, 421, 436, 442, 449, 453, 453, 471, 472, 472, 476, 479, 482, 486, 488, 494, 497, 499, 506, 509, 510, 520, 529, 531, 536, 540, 551, 561, 568, 573, 590, 603, 609, 611, 646, 651, 663, ...], 'Food and Drug Stores': [7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849, 928], 'Food, Beverages & Tobacco': [41, 44, 62, 66, 84, 94, 106, 149, 153, 161, 176, 207, 215, 242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535, 542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795, 804, 889, 902, 954], 'Health Care': [5, 6, 12, 21, 22, 33, 39, 46, 52, 55, 63, 72, 79, 86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202, 263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420, 430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618, 629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815, 818, 845, 868, 881, 883, 935, 960, 965, 977, 978], 'Hotels, Resturants & Leisure': [109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557, 562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999], 'Household Products': [34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455, 533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950, 967, 992], 'Industrials': [11, 59, 75, 93, 97, 128, 134, 148, 211, 224, 360, 377, 396, 412, 419, 539, 544, 596, 622, 623, 630, 645, 655, 658, 666, 674, 690, 757, 782, 789, 806, 813, 823, 831, 832, 835, 841, 847, 866, 867, 873, 887, 942, 947, 964, 1000], 'Materials': [126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417, 418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620, 625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857, 885, 911, 982, 986], 'Media': [53, 96, 99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681, 705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989], 'Motor Vehicles & Parts': [8, 9, 70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470, 588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979], 'Retailing': [1, 15, 28, 38, 47, 71, 89, 103, 111, 132, 136, 139, 143, 145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267, 269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379, 380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582, 592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748, 771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937, 940, 973], 'Technology': [3, 18, 20, 25, 31, 36, 51, 54, 77, 110, 113, 133, 150, 157, 158, 164, 173, 194, 219, 220, 230, 233, 284, 295, 300, 308, 313, 331, 385, 386, 400, 408, 409, 422, 451, 462, 464, 487, 491, 504, 505, 508, 513, 519, 524, 532, 543, 552, 563, 565, 584, 589, 593, 594, 612, 632, 634, 638, 649, 659, 673, 676, 678, 682, 688, 700, 725, 733, 736, 753, 760, 769, 778, 805, 830, 834, 842, 854, 864, 871, 888, 891, 893, 896, 904, 905, 906, 909, 912, 914, 919, 927, 931, 943, 944, 946, 956, 970, 971, 975, ...], 'Telecommunications': [10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619, 786], 'Transportation': [48, 58, 67, 68, 80, 129, 142, 208, 239, 270, 353, 390, 395, 405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713, 740, 800, 814, 858, 884, 930, 933, 945, 972, 974], 'Wholesalers': [57, 64, 92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285, 315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477, 484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875, 991]}

### Retrieve a group using .get_group()

In [15]:
sectors.get_group("Energy")

,Company,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,
2,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
14,Chevron,Petroleum Refining,"San Ramon, CA",131118,4587,61500
30,Phillips 66,Petroleum Refining,"Houston, TX",87169,4227,14000
32,Valero Energy,Petroleum Refining,"San Antonio, TX",81824,3990,10103
42,Marathon Petroleum,Petroleum Refining,"Findlay, OH",64566,2852,45440
...,...,...,...,...,...,...
981,WPX Energy,"Mining, Crude-Oil Production","Tulsa, OK",1958,-1727,1040
983,Adams Resources & Energy,Petroleum Refining,"Houston, TX",1944,-1,809
995,EP Energy,"Mining, Crude-Oil Production","Houston, TX",1908,-3748,665
997,Portland General Electric,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
997,Portland General Electric,Utilities: Gas and Electric,"Portland, OR",1898,172,2646

In [16]:
sectors.max()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Woodward,Aerospace and Defense,"Wichita, KS",96114,7608,197200
Apparel,Wolverine World Wide,Apparel,"Winston-Salem, NC",30601,3273,65300
Business Services,Western Union,Waste Management,"Troy, MI",19330,6328,216500
Chemicals,Westlake Chemical,Chemicals,"Wilmington, DE",48778,7685,52000
Energy,Xcel Energy,Utilities: Gas and Electric,"Washington, DC",246204,16150,75600
Engineering & Construction,Tutor Perini,Homebuilders,"Watsonville, CA",18114,803,92000
Financials,Zions Bancorp.,Securities,"Worcester, MA",210821,24442,331000
Food and Drug Stores,Whole Foods Market,Food and Drug Stores,"Woonsocket, RI",153290,5237,431000
"Food, Beverages & Tobacco",WhiteWave Foods,Tobacco,"Winston-Salem, NC",67702,7351,263000
Health Care,inVentiv Health,Wholesalers: Health Care,"York, PA",181241,18108,203500
"Hotels, Resturants & Leisure",Yum Brands,"Hotels, Casinos, Resorts","Wyomissing, PA",25413,5920,505000
Household Products,Vista Outdoor,Miscellaneous,"Zeeland, MI",78756,7036,110000
Industrials,Zebra Technologies,Miscellaneous,"Wilmerding, PA",140389,4833,333000
Materials,Worthington Industries,"Packaging, Containers","Wyomissing, PA",22534,991,60000
Media,iHeartMedia,"Publishing, Printing","Sussex, WI",52465,8382,185000
Motor Vehicles & Parts,Wabash National,Motor Vehicles and Parts,"Van Buren Township, MI",152356,9687,215000
Retailing,hhgregg,Specialty Retailers: Other,"York, PA",482130,14694,2300000
Technology,salesforce.com,Semiconductors and Other Electronic Components,"Woburn, MA",233715,53394,411798
Telecommunications,Windstream Holdings,Telecommunications,"Stamford, CT",146801,17879,281450
Transportation,YRC Worldwide,"Trucking, Truck Leasing","Thomasville, NC",58363,7610,341240
Wholesalers,World Fuel Services,Wholesalers: Food and Grocery,"Waltham, MA",48681,1472,78500

In [17]:
sectors.min()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,B/E Aerospace,Aerospace and Defense,"Berwyn, PA",1923,-240,6955
Apparel,Carter’s,Apparel,"Atlanta, GA",2204,82,5978
Business Services,ABM Industries,"Advertising, marketing","Arlington, VA",1910,-1481,2400
Chemicals,A. Schulman,Chemicals,"Allentown, PA",2084,-816,1979
Energy,AES,Energy,"Akron, OH",1898,-23119,480
Engineering & Construction,AECOM,"Engineering, Construction","Atlanta, GA",1909,-155,1036
Financials,AIG,Commercial Banks,"Atlanta, GA",1902,-1194,187
Food and Drug Stores,CVS Health,Food and Drug Stores,"Austin, TX",2151,-62,1616
"Food, Beverages & Tobacco",Alliance One International,Beverages,"Arden Hills, MN",2066,-253,1857
Health Care,AbbVie,Health Care: Insurance and Managed Care,"Abbott Park, IL",1987,-458,2924
"Hotels, Resturants & Leisure",Bloomin’ Brands,Food Services,"Ann Arbor, MI",1896,-1394,8500
Household Products,Avon Products,"Home Equipment, Furnishings","Atlanta, GA",1914,-1149,4406
Industrials,3M,Construction and Farm Machinery,"Annapolis Junction, MD",1895,-6126,4104
Materials,A-Mark Precious Metals,"Building Materials, Glass","Atlanta, GA",1924,-1642,52
Media,AMC Networks,Entertainment,"Beverly Hills, CA",1921,-881,2341
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,"Akron, OH",1986,-889,2700
Retailing,99 Cents Only Stores,"Automotive Retailing, Services","Ankeny, IA",1999,-1243,2155
Technology,Activision Blizzard,Computer Peripherals,"Angleton, TX",1920,-4359,2285
Telecommunications,AT&T,Telecommunications,"Bethpage, NY",2726,-271,2700
Transportation,Alaska Air Group,Airlines,"Atlanta, GA",1995,-191,1223
Wholesalers,Airgas,Miscellaneous,"Atlanta, GA",1917,-502,500

In [18]:
sectors.sum()

                              Revenue  Profits  Employees
Sector
Aerospace & Defense            357940    28742     968057
Apparel                         95968     8236     346397
Business Services              272195    28227    1361050
Chemicals                      243897    22628     463651
Energy                        1517809   -73447    1188927
Engineering & Construction     153983     5304     406708
Financials                    2217159   260209    3359948
Food and Drug Stores           483769    16759    1395398
Food, Beverages & Tobacco      555967    51417    1211632
Health Care                   1614707   106114    2678289
Hotels, Resturants & Leisure   169546    20697    2484245
Household Products             234737    14428     646038
Industrials                    497581    20764    1545229
Materials                      259145     4428     638123
Media                          220764    24347     550314
Motor Vehicles & Parts         482540    25898    1082560
Retailing                     1465076    47830    6227629
Technology                    1377600   180473    3578949
Telecommunications             461834    48637     832468
Transportation                 408508    44169    1536793
Wholesalers                    444800     8233     525597

In [19]:
type(sectors.sum())

pandas.core.frame.DataFrame

In [20]:
type(sectors.min())

pandas.core.frame.DataFrame

In [21]:
sectors.mean()

                                   Revenue      Profits     Employees
Sector
Aerospace & Defense           17897.000000  1437.100000  48402.850000
Apparel                        6397.866667   549.066667  23093.133333
Business Services              5337.156863   553.470588  26687.254902
Chemicals                      8129.900000   754.266667  15455.033333
Energy                        12441.057377  -602.024590   9745.303279
Engineering & Construction     5922.423077   204.000000  15642.615385
Financials                    15950.784173  1872.007194  24172.287770
Food and Drug Stores          32251.266667  1117.266667  93026.533333
Food, Beverages & Tobacco     12929.465116  1195.744186  28177.488372
Health Care                   21529.426667  1414.853333  35710.520000
Hotels, Resturants & Leisure   6781.840000   827.880000  99369.800000
Household Products             8383.464286   515.285714  23072.785714
Industrials                   10816.978261   451.391304  33591.934783
Materials                      6026.627907   102.976744  14840.069767
Media                          8830.560000   973.880000  22012.560000
Motor Vehicles & Parts        20105.833333  1079.083333  45106.666667
Retailing                     18313.450000   597.875000  77845.362500
Technology                    13505.882353  1769.343137  35087.735294
Telecommunications            30788.933333  3242.466667  55497.866667
Transportation                11347.444444  1226.916667  42688.694444
Wholesalers                   11120.000000   205.825000  13139.925000

In [22]:
sectors.Profits.sum()

Sector
Aerospace & Defense              28742
Apparel                           8236
Business Services                28227
Chemicals                        22628
Energy                          -73447
Engineering & Construction        5304
Financials                      260209
Food and Drug Stores             16759
Food, Beverages & Tobacco        51417
Health Care                     106114
Hotels, Resturants & Leisure     20697
Household Products               14428
Industrials                      20764
Materials                         4428
Media                            24347
Motor Vehicles & Parts           25898
Retailing                        47830
Technology                      180473
Telecommunications               48637
Transportation                   44169
Wholesalers                       8233
Name: Profits, dtype: int64

In [23]:
sectors[['Profits', 'Revenue']].sum()

                              Profits  Revenue
Sector
Aerospace & Defense             28742   357940
Apparel                          8236    95968
Business Services               28227   272195
Chemicals                       22628   243897
Energy                         -73447  1517809
Engineering & Construction       5304   153983
Financials                     260209  2217159
Food and Drug Stores            16759   483769
Food, Beverages & Tobacco       51417   555967
Health Care                    106114  1614707
Hotels, Resturants & Leisure    20697   169546
Household Products              14428   234737
Industrials                     20764   497581
Materials                        4428   259145
Media                           24347   220764
Motor Vehicles & Parts          25898   482540
Retailing                       47830  1465076
Technology                     180473  1377600
Telecommunications              48637   461834
Transportation                  44169   408508
Wholesalers                      8233   444800

### grouping by multiple column

In [24]:
compaines = pd.read_csv('../../datasets/fortune1000.csv', index_col=['Rank'])

In [25]:
sectors_industry = compaines.groupby(by=['Sector', 'Industry'])

In [26]:
sectors_industry

In [27]:
sectors_industry.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            20
Apparel              Apparel                                          15
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         3
                                                                      ..
Transportation       Trucking, Truck Leasing                           9
Wholesalers          Miscellaneous                                     1
                     Wholesalers: Diversified                         25
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
Length: 79, dtype: int64

In [28]:
sectors_industry.min()

                                                                                  Company  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                                   B/E Aerospace
Apparel             Apparel                                                      Carter’s
Business Services   Advertising, marketing                              Interpublic Group
                    Diversified Outsourcing Services                       ABM Industries
                    Education                                      Apollo Education Group
...                                                                                   ...
Transportation      Trucking, Truck Leasing                                        Amerco
Wholesalers         Miscellaneous                                                  Univar
                    Wholesalers: Diversified                                       Airgas
                    Wholesalers: Electronics and Office Equipment       Arrow Electronics
                    Wholesalers: Food and Grocery                       Core-Mark Holding

                                                                            Location  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                                 Berwyn, PA
Apparel             Apparel                                              Atlanta, GA
Business Services   Advertising, marketing                              New York, NY
                    Diversified Outsourcing Services                   Arlington, VA
                    Education                                          Arlington, VA
...                                                                              ...
Transportation      Trucking, Truck Leasing                           Fort Smith, AR
Wholesalers         Miscellaneous                                  Downers Grove, IL
                    Wholesalers: Diversified                             Atlanta, GA
                    Wholesalers: Electronics and Office Equipment     Centennial, CO
                    Wholesalers: Food and Grocery                   Byron Center, MI

                                                                   Revenue  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                             1923
Apparel             Apparel                                           2204
Business Services   Advertising, marketing                            7614
                    Diversified Outsourcing Services                  2383
                    Education                                         1910
...                                                                    ...
Transportation      Trucking, Truck Leasing                           2094
Wholesalers         Miscellaneous                                     8982
                    Wholesalers: Diversified                          1917
                    Wholesalers: Electronics and Office Equipment     3219
                    Wholesalers: Food and Grocery                     7652

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                             -240
Apparel             Apparel                                             82
Business Services   Advertising, marketing                             455
                    Diversified Outsourcing Services                   -12
                    Education                                         -101
...                                                                    ...
Transportation      Trucking, Truck Leasing                              1
Wholesalers         Miscellaneous                                       17
                    Wholesalers: Diversified                          -502
                    Wholesalers: Electronics and Office Equipment      -44
                    Wholesalers: Food and Grocery                       52

                                                                   Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                               6955
Apparel             Apparel                                             5978
Business Services   Advertising, marketing                             49200
                    Diversified Outsourcing Services                    2400
                    Education                                          11585
...                                                                      ...
Transportation      Trucking, Truck Leasing                             1223
Wholesalers         Miscellaneous                                       9200
                    Wholesalers: Diversified                             500
                    Wholesalers: Electronics and Office Equipment       2000
                    Wholesalers: Food and Grocery                       6655

[79 rows x 5 columns]

In [29]:
sectors_industry.Revenue.sum()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            357940
Apparel              Apparel                                           95968
Business Services    Advertising, marketing                            22748
                     Diversified Outsourcing Services                  64829
                     Education                                          7485
                                                                       ...
Transportation       Trucking, Truck Leasing                           35950
Wholesalers          Miscellaneous                                      8982
                     Wholesalers: Diversified                         176138
                     Wholesalers: Electronics and Office Equipment    147906
                     Wholesalers: Food and Grocery                    111774
Name: Revenue, Length: 79, dtype: int64

### agg(), it accepts a dictionary with key as the column and the value as the operation

In [37]:
sectors.agg({'Profits': 'sum'})

                              Profits
Sector
Aerospace & Defense             28742
Apparel                          8236
Business Services               28227
Chemicals                       22628
Energy                         -73447
Engineering & Construction       5304
Financials                     260209
Food and Drug Stores            16759
Food, Beverages & Tobacco       51417
Health Care                    106114
Hotels, Resturants & Leisure    20697
Household Products              14428
Industrials                     20764
Materials                        4428
Media                           24347
Motor Vehicles & Parts          25898
Retailing                       47830
Technology                     180473
Telecommunications              48637
Transportation                  44169
Wholesalers                      8233

In [38]:
sectors.agg({'Profits': 'sum', 'Employees': 'mean'})

                              Profits     Employees
Sector
Aerospace & Defense             28742  48402.850000
Apparel                          8236  23093.133333
Business Services               28227  26687.254902
Chemicals                       22628  15455.033333
Energy                         -73447   9745.303279
Engineering & Construction       5304  15642.615385
Financials                     260209  24172.287770
Food and Drug Stores            16759  93026.533333
Food, Beverages & Tobacco       51417  28177.488372
Health Care                    106114  35710.520000
Hotels, Resturants & Leisure    20697  99369.800000
Household Products              14428  23072.785714
Industrials                     20764  33591.934783
Materials                        4428  14840.069767
Media                           24347  22012.560000
Motor Vehicles & Parts          25898  45106.666667
Retailing                       47830  77845.362500
Technology                     180473  35087.735294
Telecommunications              48637  55497.866667
Transportation                  44169  42688.694444
Wholesalers                      8233  13139.925000

### agg(), accepts a list of operations

In [39]:
sectors.agg(['sum', 'size', 'min'])

                                                                        Company  \
                                                                            sum
Sector
Aerospace & Defense           BoeingUnited TechnologiesLockheed MartinGenera...
Apparel                       NikeVFPVHRalph LaurenHanesbrandsLevi StraussCo...
Business Services             ManpowerGroupOmnicom GroupAramarkVisaWaste Man...
Chemicals                     Dow ChemicalDuPontPPG IndustriesMonsantoEcolab...
Energy                        Exxon MobilChevronPhillips 66Valero EnergyMara...
Engineering & Construction    FluorAECOMJacobs Engineering GroupD.R. HortonL...
Financials                    Berkshire HathawayFannie MaeJ.P. Morgan ChaseB...
Food and Drug Stores          CVS HealthKrogerWalgreens Boots AlliancePublix...
Food, Beverages & Tobacco     Archer Daniels MidlandPepsiCoCoca-ColaTyson Fo...
Health Care                   McKessonUnitedHealth GroupAmerisourceBergenCar...
Hotels, Resturants & Leisure  McDonald’sStarbucksMarriott InternationalYum B...
Household Products            Procter & GambleKimberly-ClarkColgate-Palmoliv...
Industrials                   General ElectricCaterpillarHoneywell Internati...
Materials                     AlcoaInternational PaperNucorUnited States Ste...
Media                         DisneyTwenty-First Century FoxTime WarnerCBSVi...
Motor Vehicles & Parts        General MotorsFord MotorJohnson ControlsPaccar...
Retailing                     WalmartCostcoHome DepotTargetLowe’sBest BuyTJX...
Technology                    AppleAmazon.comHPMicrosoftIBMAlphabetIntelCisc...
Telecommunications            AT&TVerizonComcastTime Warner CableCenturyLink...
Transportation                UPSFedExAmerican Airlines GroupDelta Air Lines...
Wholesalers                   SyscoIngram MicroWorld Fuel ServicesAvnetTech ...

                                                                  \
                             size                            min
Sector
Aerospace & Defense            20                  B/E Aerospace
Apparel                        15                       Carter’s
Business Services              51                 ABM Industries
Chemicals                      30                    A. Schulman
Energy                        122                            AES
Engineering & Construction     26                          AECOM
Financials                    139                            AIG
Food and Drug Stores           15                     CVS Health
Food, Beverages & Tobacco      43     Alliance One International
Health Care                    75                         AbbVie
Hotels, Resturants & Leisure   25                Bloomin’ Brands
Household Products             28                  Avon Products
Industrials                    46                             3M
Materials                      43         A-Mark Precious Metals
Media                          25                   AMC Networks
Motor Vehicles & Parts         24  Allison Transmission Holdings
Retailing                      80           99 Cents Only Stores
Technology                    102            Activision Blizzard
Telecommunications             15                           AT&T
Transportation                 36               Alaska Air Group
Wholesalers                    40                         Airgas

                                                                       Industry  \
                                                                            sum
Sector
Aerospace & Defense           Aerospace and DefenseAerospace and DefenseAero...
Apparel                       ApparelApparelApparelApparelApparelApparelAppa...
Business Services             Temporary HelpAdvertising, marketingDiversifie...
Chemicals                     ChemicalsChemicalsChemicalsChemicalsChemicalsC...
Energy                        Petroleum RefiningPetroleum RefiningPetroleum ...
Engineering & Construction    Engineering, ConstructionEngineering, Construc...
Financials                    Insurance: Property and Casualty (Stock)Divers...
Food and Drug Stores          Food and Drug StoresFood and Drug StoresFood a...
Food, Beverages & Tobacco     Food ProductionFood Consumer ProductsBeverages...
Health Care                   Wholesalers: Health CareHealth Care: Insurance...
Hotels, Resturants & Leisure  Food ServicesFood ServicesHotels, Casinos, Res...
Household Products            Household and Personal ProductsHousehold and P...
Industrials                   Industrial MachineryConstruction and Farm Mach...
Materials                     MetalsPackaging, ContainersMetalsMetalsPackagi...
Media                         EntertainmentEntertainmentEntertainmentEnterta...
Motor Vehicles & Parts        Motor Vehicles and PartsMotor Vehicles and Par...
Retailing                     General MerchandisersSpecialty Retailers: Othe...
Technology                    Computers, Office EquipmentInternet Services a...
Telecommunications            TelecommunicationsTelecommunicationsTelecommun...
Transportation                Mail, Package, and Freight DeliveryMail, Packa...
Wholesalers                   Wholesalers: Food and GroceryWholesalers: Elec...

                                                                            \
                             size                                      min
Sector
Aerospace & Defense            20                    Aerospace and Defense
Apparel                        15                                  Apparel
Business Services              51                   Advertising, marketing
Chemicals                      30                                Chemicals
Energy                        122                                   Energy
Engineering & Construction     26                Engineering, Construction
Financials                    139                         Commercial Banks
Food and Drug Stores           15                     Food and Drug Stores
Food, Beverages & Tobacco      43                                Beverages
Health Care                    75  Health Care: Insurance and Managed Care
Hotels, Resturants & Leisure   25                            Food Services
Household Products             28              Home Equipment, Furnishings
Industrials                    46          Construction and Farm Machinery
Materials                      43                Building Materials, Glass
Media                          25                            Entertainment
Motor Vehicles & Parts         24                 Motor Vehicles and Parts
Retailing                      80           Automotive Retailing, Services
Technology                    102                     Computer Peripherals
Telecommunications             15                       Telecommunications
Transportation                 36                                 Airlines
Wholesalers                    40                            Miscellaneous

                                                                       Location  \
                                                                            sum
Sector
Aerospace & Defense           Chicago, ILFarmington, CTBethesda, MDFalls Chu...
Apparel                       Beaverton, ORGreensboro, NCNew York, NYNew Yor...
Business Services             Milwaukee, WINew York, NYPhiladelphia, PAFoste...
Chemicals                     Midland, MIWilmington, DEPittsburgh, PASt. Lou...
Energy                        Irving, TXSan Ramon, CAHouston, TXSan Antonio,...
Engineering & Construction    Irving, TXLos Angeles, CAPasadena, CAFort Wort...
Financials                    Omaha, NEWashington, DCNew York, NYCharlotte, ...
Food and Drug Stores          Woonsocket, RICincinnati, OHDeerfield, ILLakel...
Food, Beverages & Tobacco     Chicago, ILPurchase, NYAtlanta, GASpringdale, ...
Health Care                   San Francisco, CAMinnetonka, MNChesterbrook, P...
Hotels, Resturants & Leisure  Oak Brook, ILSeattle, WABethesda, MDLouisville...
Household Products            Cincinnati, OHIrving, TXNew York, NYNew Britai...
Industrials                   Fairfield, CTPeoria, ILMorris Plains, NJSt. Pa...
Materials                     New York, NYMemphis, TNCharlotte, NCPittsburgh...
Media                         Burbank, CANew York, NYNew York, NYNew York, N...
Motor Vehicles & Parts        Detroit, MIDearborn, MIMilwaukee, WIBellevue, ...
Retailing                     Bentonville, ARIssaquah, WAAtlanta, GAMinneapo...
Technology                    Cupertino, CASeattle, WAPalo Alto, CARedmond, ...
Telecommunications            Dallas, TXNew York, NYPhiladelphia, PANew York...
Transportation                Atlanta, GAMemphis, TNFort Worth, TXAtlanta, G...
Wholesalers                   Houston, TXIrvine, CAMiami, FLPhoenix, AZClear...

                                                           Revenue             \
                             size                     min      sum size   min
Sector
Aerospace & Defense            20              Berwyn, PA   357940   20  1923
Apparel                        15             Atlanta, GA    95968   15  2204
Business Services              51           Arlington, VA   272195   51  1910
Chemicals                      30           Allentown, PA   243897   30  2084
Energy                        122               Akron, OH  1517809  122  1898
Engineering & Construction     26             Atlanta, GA   153983   26  1909
Financials                    139             Atlanta, GA  2217159  139  1902
Food and Drug Stores           15              Austin, TX   483769   15  2151
Food, Beverages & Tobacco      43         Arden Hills, MN   555967   43  2066
Health Care                    75         Abbott Park, IL  1614707   75  1987
Hotels, Resturants & Leisure   25           Ann Arbor, MI   169546   25  1896
Household Products             28             Atlanta, GA   234737   28  1914
Industrials                    46  Annapolis Junction, MD   497581   46  1895
Materials                      43             Atlanta, GA   259145   43  1924
Media                          25       Beverly Hills, CA   220764   25  1921
Motor Vehicles & Parts         24               Akron, OH   482540   24  1986
Retailing                      80              Ankeny, IA  1465076   80  1999
Technology                    102            Angleton, TX  1377600  102  1920
Telecommunications             15            Bethpage, NY   461834   15  2726
Transportation                 36             Atlanta, GA   408508   36  1995
Wholesalers                    40             Atlanta, GA   444800   40  1917

                             Profits             Employees
                                 sum size    min       sum size   min
Sector
Aerospace & Defense            28742   20   -240    968057   20  6955
Apparel                         8236   15     82    346397   15  5978
Business Services              28227   51  -1481   1361050   51  2400
Chemicals                      22628   30   -816    463651   30  1979
Energy                        -73447  122 -23119   1188927  122   480
Engineering & Construction      5304   26   -155    406708   26  1036
Financials                    260209  139  -1194   3359948  139   187
Food and Drug Stores           16759   15    -62   1395398   15  1616
Food, Beverages & Tobacco      51417   43   -253   1211632   43  1857
Health Care                   106114   75   -458   2678289   75  2924
Hotels, Resturants & Leisure   20697   25  -1394   2484245   25  8500
Household Products             14428   28  -1149    646038   28  4406
Industrials                    20764   46  -6126   1545229   46  4104
Materials                       4428   43  -1642    638123   43    52
Media                          24347   25   -881    550314   25  2341
Motor Vehicles & Parts         25898   24   -889   1082560   24  2700
Retailing                      47830   80  -1243   6227629   80  2155
Technology                    180473  102  -4359   3578949  102  2285
Telecommunications             48637   15   -271    832468   15  2700
Transportation                 44169   36   -191   1536793   36  1223
Wholesalers                     8233   40   -502    525597   40   500

### iterate through groups

In [43]:
for sector, data in sectors:
    print(data[['Company', 'Profits']])

                            Company  Profits
Rank
24                           Boeing     5176
45              United Technologies     7608
60                  Lockheed Martin     3605
88                 General Dynamics     2965
118                Northrop Grumman     1990
120                        Raytheon     2074
209                         Textron      697
245              L-3 Communications     -240
282             Precision Castparts     1530
378   Huntington Ingalls Industries      404
389     Spirit AeroSystems Holdings      789
490                Rockwell Collins      686
560                     Orbital ATK      159
605                   Triumph Group      239
785                   B/E Aerospace      286
788                 TransDigm Group      447
836                            Moog      132
903                  Curtiss-Wright      146
958                        Woodward      182
987           Delta Tucker Holdings     -133
                   Company  Profits
Rank
91                    Nike     3273
231                     VF     1232
340                    PVH      572
354           Ralph Lauren      702
448            Hanesbrands      429
547           Levi Strauss      209
575                  Coach      402
597           Under Armour      233
683           Fossil Group      221
695        Skechers U.S.A.      232
726               Carter’s      238
794   Wolverine World Wide      123
877    G-III Apparel Group      114
882    Columbia Sportswear      174
917                  Guess       82
                                     Company  Profits
Rank
144                            ManpowerGroup      419
186                            Omnicom Group     1094
199                                  Aramark      236
204                                     Visa     6328
221                         Waste Management      753
248                                      ADP     1453
249                               First Data    -1481
294                               MasterCard     3808
307                          PayPal Holdings     1228
312                        Republic Services      750
355                        Interpublic Group      455
392   Fidelity National Information Services      632
404                    Alliance Data Systems      597
440                           United Rentals      585
467                           Kelly Services       54
468                            Western Union      838
481                               S&P Global     1156
485                           ABM Industries       76
492                                   Fiserv      712
503                Robert Half International      358
545                                   Cintas      431
626                            Towers Watson      385
635                                      ADT      296
652                                  Moody’s      941
677                            Clean Harbors       44
694                                   Vantiv      148
714                                  Brink’s      -12
729                            Iron Mountain      123
734              Service Corp. International      234
735                               Stericycle      267
737                          Graham Holdings     -101
744                                Convergys      169
767                              DST Systems      358
776                    Total System Services      364
777                          Global Payments      278
783                                  Paychex      675
791                                 TrueBlue       71
792           Broadridge Financial Solutions      287
796                Heartland Payment Systems       85
801                                  Equifax      429
803                             TriNet Group       32
816                                Insperity       39
819            ServiceMaster Global Holdings      160
820                   Apollo Education Group       30
869                                     West      242
870                           Public Storage     1311
886                               IHS Markit      240
939                        Waste Connections      -96
951                            On Assignment       98
952                         Verisk Analytics      508
993                    DeVry Education Group      140
                                 Company  Profits
Rank
56                          Dow Chemical     7685
101                               DuPont     1953
182                       PPG Industries     1406
189                             Monsanto     2314
206                               Ecolab     1002
253                     Sherwin-Williams     1054
262                              Praxair     1547
277                             Huntsman       93
288             Air Products & Chemicals     1278
296                     Eastman Chemical      848
316                               Mosaic     1000
538                    RPM International      240
549                    Westlake Chemical      646
555                              Valspar      400
566               CF Industries Holdings      700
580                               Hexion      -40
613                               Axiall     -816
624                            Albemarle      335
654                                  FMC      489
668                              PolyOne      145
717                           W.R. Grace      144
720   International Flavors & Fragrances      419
724                   Scotts Miracle-Gro      160
758                                Cabot     -334
761                                 Olin       -1
829          Platform Specialty Products     -309
865                          A. Schulman       27
898                         MPM Holdings      -83
934                            NewMarket      239
949                          H.B. Fuller       87
                        Company  Profits
Rank
2                   Exxon Mobil    16150
14                      Chevron     4587
30                  Phillips 66     4227
32                Valero Energy     3990
42           Marathon Petroleum     2852
...                         ...      ...
981                  WPX Energy    -1727
983    Adams Resources & Energy       -1
995                   EP Energy    -3748
997   Portland General Electric      172
997   Portland General Electric      172

[122 rows x 2 columns]
                       Company  Profits
Rank
155                      Fluor      413
156                      AECOM     -155
235   Jacobs Engineering Group      303
260                D.R. Horton      751
301                     Lennar      803
314         Peter Kiewit Sons’      251
352            Quanta Services      311
381                EMCOR Group      172
433                 PulteGroup      494
478                  CH2M Hill       80
498                        NVR      383
501                        KBR      203
516               Tutor Perini       45
572                     MasTec      -79
576              Toll Brothers      363
640          CalAtlantic Group      214
719                    KB Home       85
738       Taylor Morrison Home       61
822             Meritage Homes      129
863           TRI Pointe Group      206
874       Granite Construction       61
892                 Tetra Tech       39
929      Hovnanian Enterprises      -16
963           Dycom Industries       84
985          Primoris Services       37
994               MDC Holdings       66
                           Company  Profits
Rank
4               Berkshire Hathaway    24083
16                      Fannie Mae    10954
23               J.P. Morgan Chase    24442
26           Bank of America Corp.    15888
27                     Wells Fargo    22894
...                            ...      ...
938                        Popular      895
959   Stewart Information Services       -6
976            First Republic Bank      522
988   Hospitality Properties Trust      166
996     New York Community Bancorp      -47

[139 rows x 2 columns]
                       Company  Profits
Rank
7                   CVS Health     5237
17                      Kroger     2039
19    Walgreens Boots Alliance     4220
87        Publix Super Markets     1965
107                   Rite Aid     2109
160                  Supervalu      192
181         Whole Foods Market      536
595       Smart & Final Stores       38
614             Ingles Markets       59
631     Sprouts Farmers Market      129
669          Diplomat Pharmacy       26
756               Weis Markets       59
809               GNC Holdings      219
849               Tops Holding      -62
928                     Fred’s       -7
                          Company  Profits
Rank
41         Archer Daniels Midland     1849
44                        PepsiCo     5452
62                      Coca-Cola     7351
66                    Tyson Foods     1220
84                            CHS      781
94         Mondelez International     7267
106   Philip Morris International     6873
149                  Altria Group     5241
153                   Kraft Heinz      634
161                 General Mills     1221
176                 ConAgra Foods     -253
207                       Kellogg      614
215                  Land O’Lakes      308
242             Leucadia National      284
266             Reynolds American     3253
304                  Hormel Foods      686
336                    Dean Foods       -9
337                 Campbell Soup      691
362                       Hershey      513
397   Coca-Cola European Partners      596
413       Dr Pepper Snapple Group      764
429          Constellation Brands      839
452                  J.M. Smucker      345
456                     Ingredion      402
460                      Seaboard      171
535                 Post Holdings     -115
542         Keurig Green Mountain      498
567                     McCormick      402
574                     Andersons      -13
587        Mead Johnson Nutrition      654
608               WhiteWave Foods      168
615                 Flowers Foods      189
636          Molson Coors Brewing      360
664           Darling Ingredients       79
686               TreeHouse Foods      115
702                  Brown-Forman      684
770               Sanderson Farms      216
787              Monster Beverage      547
795          Hain Celestial Group      168
804                Pinnacle Foods      213
889            Coca-Cola Bottling       59
902                     Universal      115
954    Alliance One International      -15
                      Company  Profits
Rank
5                    McKesson     1476
6          UnitedHealth Group     5813
12          AmerisourceBergen     -135
21            Cardinal Health     1215
22    Express Scripts Holding     2476
...                       ...      ...
935                       VCA      211
960                PharMerica       35
965      Bio-Rad Laboratories      113
977         Hill-Rom Holdings       48
978        Providence Service       84

[75 rows x 2 columns]
                               Company  Profits
Rank
109                         McDonald’s     4529
146                          Starbucks     2757
195             Marriott International      859
218                         Yum Brands     1293
241                    Las Vegas Sands     1966
254          Hilton Worldwide Holdings     1404
309          MGM Resorts International     -448
371                 Darden Restaurants      710
444          Starwood Hotels & Resorts      489
466                  Wyndham Worldwide      612
534              Caesars Entertainment     5920
546             Chipotle Mexican Grill      476
557                    Bloomin’ Brands      127
562                       Hyatt Hotels      124
585                       Wynn Resorts      195
731              Brinker International      197
763   Cracker Barrel Old Country Store      164
764               Penn National Gaming        1
779                   Scientific Games    -1394
797                       Panera Bread      149
895             Pinnacle Entertainment       49
915                     Domino’s Pizza      193
918                        Boyd Gaming       47
941                 Cheesecake Factory      117
999                            Wendy’s      161
                             Company  Profits
Rank
34                  Procter & Gamble     7036
151                   Kimberly-Clark     1013
174                Colgate-Palmolive     1384
256           Stanley Black & Decker      884
261                     Estee Lauder     1089
328                           Jarden      147
338                Mohawk Industries      615
345                            Masco      355
370                    Avon Products    -1149
434                    Newell Brands      350
441                        HRG Group     -557
450                           Mattel      369
455                           Clorox      580
533   Fortune Brands Home & Security      315
550                           Hasbro      452
554                             Coty      233
601                  Leggett & Platt      325
665                  Church & Dwight      410
699       Tempur Sealy International       74
716                        Steelcase       86
856           Edgewell Personal Care     -275
890                              HNI      105
900                Tupperware Brands      186
907              Nu Skin Enterprises      133
932                    Herman Miller       98
950                    Vista Outdoor       80
967                          Griffon       34
992                           Revlon       56
                                  Company  Profits
Rank
11                       General Electric    -6126
59                            Caterpillar     2102
75                Honeywell International     4768
93                                     3M     4833
97                                  Deere     1940
128                      Emerson Electric     2710
134                             Whirlpool      783
148                               Cummins     1399
211                   Illinois Tool Works     1899
224                       Parker-Hannifin     1012
360                                  AGCO      266
377                                 Dover      870
396                                 Terex      146
412                   Rockwell Automation      828
419       Harman International Industries      343
539                             Flowserve      268
544                         General Cable     -122
596                                Colfax      168
622                                 Xylem      340
623                    Zebra Technologies     -137
630                               Snap-on      479
645                          Regal Beloit      143
655                  Lennox International      187
658                             Manitowoc       64
666                               Hubbell      277
674   Westinghouse Air Brake Technologies      399
690                            Joy Global    -1178
757                                Timken      -71
782                                 Crane      229
789                         Acuity Brands      222
806                            Kennametal     -374
813                    Valmont Industries       40
823        Hyster-Yale Materials Handling       75
831                            A.O. Smith      283
832             Lincoln Electric Holdings      128
835                                Nortek      -27
841                               EnerSys      181
847                                   ITT      352
866                                  Toro      202
867                              SPX FLOW       88
873                             Donaldson      208
887                                Belden       66
942                    Mueller Industries       88
947                               Rexnord       84
964                                  IDEX      283
1000                    Briggs & Stratton       46
                         Company  Profits
Rank
126                        Alcoa     -322
127          International Paper      938
170                        Nucor      358
244          United States Steel    -1642
251                     WestRock      507
303    Reliance Steel & Aluminum      312
321               Crown Holdings      393
341                         Ball      281
356               Steel Dynamics     -130
373                 Weyerhaeuser      506
375                   Sealed Air      335
383             AK Steel Holding     -509
417            Commercial Metals      142
418               Owens-Illinois      -74
426       A-Mark Precious Metals        7
435               Avery Dennison      274
446   Packaging Corp. of America      437
480                Owens Corning      330
489                       Domtar      142
514              Sonoco Products      250
518         Berry Plastics Group       86
577    Graphic Packaging Holding      230
586                        Bemis      239
616                          USG      991
617              Silgan Holdings      172
620       Allegheny Technologies     -378
625     Resolute Forest Products     -257
628                        Greif       72
637         Builders FirstSource      -23
639                     Carlisle      320
641    Martin Marietta Materials      289
660             Vulcan Materials      221
667       Worthington Industries       77
687                       Aleris       49
691              Ryerson Holding       -1
751    Universal Forest Products       81
774   KapStone Paper & Packaging      106
793                        Verso     -477
857   Armstrong World Industries       94
885                   AptarGroup      199
911         Carpenter Technology       59
982             Century Aluminum      -59
986   Schnitzer Steel Industries     -197
                           Company  Profits
Rank
53                          Disney     8382
96        Twenty-First Century Fox     8306
99                     Time Warner     3833
203                            CBS     1413
213                         Viacom     1922
255          R.R. Donnelley & Sons      151
327                     News Corp.     -147
366      Live Nation Entertainment      -33
406       Discovery Communications     1034
414                    iHeartMedia     -755
525                  Liberty Media       64
530                  Quad/Graphics     -642
681                          TEGNA      460
705      Regal Entertainment Group      153
707                           Time     -881
722   Scripps Networks Interactive      607
741             Warner Music Group      -91
752                        Gannett      146
759       Univision Communications      -45
762              Cinemark Holdings      217
821                   AMC Networks      367
913       Sinclair Broadcast Group      172
968             American Greetings       65
969                  Tribune Media     -320
989                         Cenveo      -31
                            Company  Profits
Rank
8                    General Motors     9687
9                        Ford Motor     7373
70                 Johnson Controls     1563
147                          Paccar     1604
154                            Lear      746
169          Goodyear Tire & Rubber      307
281          Navistar International     -184
310                         Autoliv      457
334                         Tenneco      247
339                      BorgWarner      610
424                         Oshkosh      230
428                    Dana Holding      159
470                         Visteon     2284
588                    Tesla Motors     -889
591                 Thor Industries      199
604   American Axle & Manufacturing      236
647                         Meritor       64
670        Cooper-Standard Holdings      112

In [60]:
df = pd.DataFrame(columns=compaines.columns)
for sector, data in sectors:
    highest_profits_company_in_group = data.nlargest(2, 'Profits')
    df = df.append(highest_profits_company_in_group)

In [61]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
45,United Technologies,Aerospace & Defense,Aerospace and Defense,"Farmington, CT",61047,7608,197200
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
231,VF,Apparel,Apparel,"Greensboro, NC",12377,1232,64000
204,Visa,Business Services,Financial Data Services,"Foster City, CA",13880,6328,11300
294,MasterCard,Business Services,Financial Data Services,"Purchase, NY",9667,3808,11300
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
189,Monsanto,Chemicals,Chemicals,"St. Louis, MO",15001,2314,24000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
14,Chevron,Energy,Petroleum Refining,"San Ramon, CA",131118,4587,61500
301,Lennar,Engineering & Construction,Homebuilders,"Miami, FL",9474,803,7749
260,D.R. Horton,Engineering & Construction,Homebuilders,"Fort Worth, TX",10824,751,6230
23,J.P. Morgan Chase,Financials,Commercial Banks,"New York, NY",101006,24442,234598
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
19,Walgreens Boots Alliance,Food and Drug Stores,Food and Drug Stores,"Deerfield, IL",103444,4220,302500
62,Coca-Cola,"Food, Beverages & Tobacco",Beverages,"Atlanta, GA",44294,7351,123200
94,Mondelez International,"Food, Beverages & Tobacco",Food Consumer Products,"Deerfield, IL",29636,7267,99000
86,Gilead Sciences,Health Care,Pharmaceuticals,"Foster City, CA",32639,18108,8000
39,Johnson & Johnson,Health Care,Pharmaceuticals,"New Brunswick, NJ",70074,15409,127100
534,Caesars Entertainment,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Las Vegas, NV",4654,5920,33000
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
174,Colgate-Palmolive,Household Products,Household and Personal Products,"New York, NY",16034,1384,37900
93,3M,Industrials,Miscellaneous,"St. Paul, MN",30274,4833,89446
75,Honeywell International,Industrials,"Electronics, Electrical Equip.","Morris Plains, NJ",38581,4768,129000
616,USG,Materials,"Building Materials, Glass","Chicago, IL",3776,991,8900
127,International Paper,Materials,"Packaging, Containers","Memphis, TN",22365,938,56000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
96,Twenty-First Century Fox,Media,Entertainment,"New York, NY",28987,8306,20500
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
9,Ford Motor,Motor Vehicles & Parts,Motor Vehicles and Parts,"Dearborn, MI",149558,7373,199000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
28,Home Depot,Retailing,Specialty Retailers: Other,"Atlanta, GA",88519,7009,385000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
36,Alphabet,Technology,Internet Services and Retailing,"Mountain View, CA",74989,16348,61814
13,Verizon,Telecommunications,Telecommunications,"New York, NY",131620,17879,177700
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
67,American Airlines Group,Transportation,Airlines,"Fort Worth, TX",40990,7610,118500
80,United Continental Holdings,Transportation,Airlines,"Chicago, IL",37864,7340,84000
320,HD Supply Holdings,Wholesalers,Wholesalers: Diversified,"Atlanta, GA",8779,1472,14000
285,W.W. Grainger,Wholesalers,Wholesalers: Diversified,"Lake Forest, IL",9973,769,25100

In [62]:
df = pd.DataFrame(columns=compaines.columns)
locationGroupBy = compaines.groupby('Location')

In [63]:
locationGroupBy

In [65]:
for city, data in locationGroupBy:
    highest_revenue_company_in_group = data.nlargest(1, 'Revenue')
    df = df.append(highest_revenue_company_in_group)

In [66]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
138,Abbott Laboratories,Health Care,Medical Products and Equipment,"Abbott Park, IL",20661,4423,74000
169,Goodyear Tire & Rubber,Motor Vehicles & Parts,Motor Vehicles and Parts,"Akron, OH",16443,307,66000
288,Air Products & Chemicals,Chemicals,Chemicals,"Allentown, PA",9895,1278,19550
830,Benchmark Electronics,Technology,Semiconductors and Other Electronic Components,"Angleton, TX",2541,95,10500
374,Casey’s General Stores,Retailing,Specialty Retailers: Other,"Ankeny, IA",7052,181,22408
...,...,...,...,...,...,...,...
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
506,Hanover Insurance Group,Financials,Insurance: Property and Casualty (Stock),"Worcester, MA",5034,332,4800
764,Penn National Gaming,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Wyomissing, PA",2838,1,18204
773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100
932,Herman Miller,Household Products,"Home Equipment, Furnishings","Zeeland, MI",2142,98,7510

### For each unique location in the companies dataframe, we are going to pull the company that has the highest revenue